### ISSUE TITLE
Support to run sql files 

### ISSUE THREAD

**Issue by igor-kramer** [whisklabs/airflow-clickhouse-plugin#35]
Hello!
Will be great to have ability to run queries from .sql files like MySQLOperator:

```python
mysql_task = MySqlOperator(
    task_id='create_table_mysql_external_file',
    sql='/scripts/drop_table.sql',
    dag=dag,
)
```

**Comment by bryzgaloff** [comment]
Since this file has to be located on Airflow worker node, won't it be easier to you to simply:

```python
with open('/scripts/drop_table.sql') as sql_file:
    sql_query = sql_file.read()
with DAG(…) as dag:
    task = ClickHouseOperator(…, sql=sql_query)
```

No need to complexify operators' implementation with smth built-in to Python. Plugin's responsibility is to provide you with a connection to ClickHouse server using Airflow primitives while operator's configuration (including SQL file resolution) is DAG's author responsibility. Moreover, these are two extra lines of Python code.
